#!/usr/bin/env node
// One parser and one resolver for ai-factory/models.yaml, shared by the headless runner, the
// interactive dispatch step, adapter sync and doctor. Configuration is data: a model is only
// ever passed as one argument or one quoted field, never through a shell.
//
//   node ai-factory/make/models.js dispatch --host claude|codex --task <task> [--task-model <v>]
//   node ai-factory/make/models.js record --dispatch <id> --outcome <outcome> [--worker <id>]
//   node ai-factory/make/models.js show --tool claude|codex --task <task>
//   node ai-factory/make/models.js doctor
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const TOOLS = ["claude", "codex"];
const TASK_NAME = /^[a-z][a-z0-9-]*$/;
// An interactive override travels through one shell word the session writes, so it is limited
// to the characters model ids and gateway aliases use. models.yaml itself accepts any literal.
const OVERRIDE = /^[A-Za-z0-9._:/@+-]{1,200}$/;
const TOP_LEVEL = ["claude", "codex", "review", "pricing", "routing"];
const SELECTION_SCHEMA = "t4.model-selection.v1";
const DISPATCH_SCHEMA = "t4.model-dispatch.v1";
const MARKER = "<!-- Generated by t4; canonical content lives in ai-factory/. -->";
const TOML_MARKER = "# Generated by t4; canonical content lives in ai-factory/.";
const ADAPTER_DIRS = { claude: ".claude/agents", codex: ".codex/agents" };
const ADAPTER_EXT = { claude: ".md", codex: ".toml" };
const LABELS = {
	explicit: "explicit override",
	"explicit-inherit": "explicit inherit",
	task: "task default",
	"review-default": "review default",
	"tool-default": "tool default",
	"cli-default": "CLI default",
};

function scalar(text, line) {
	const value = text.trim();
	if (!value || value.startsWith("#")) return "";
	if (value.startsWith('"')) {
		const match = value.match(/^("(?:[^"\\]|\\.)*")(?:\s+#.*)?$/);
		if (!match) throw new Error(`Invalid quoted model on line ${line}`);
		return JSON.parse(match[1]);
	}
	if (value.startsWith("'")) {
		const match = value.match(/^'((?:[^']|'')*)'(?:\s+#.*)?$/);
		if (!match) throw new Error(`Invalid quoted model on line ${line}`);
		return match[1].replace(/''/g, "'");
	}
	if (/^[|>{[&*!]/.test(value))
		throw new Error(`Unsupported model syntax on line ${line}`);
	return value.replace(/\s+#.*$/, "").trim();
}

function model(raw, line) {
	const value = scalar(raw, line);
	if (/[\r\n\0]/.test(value)) throw new Error(`Invalid model on line ${line}`);
	return value;
}

// The supported subset: three top-level scalars, `pricing` (indented rows the hooks read) and
// `routing` (enabled + tasks.<task>.<tool>), two spaces per level. Anything else is an error
// naming its line, so a typo can never quietly select a different model.
function parseModels(content) {
	const result = {
		routing: { present: false, enabled: false, tasks: {} },
		digest: digest(content),
	};
	const seen = new Set();
	let section = null;
	let routingKeys;
	let inTasks = false;
	let task = null;
	let taskKeys;
	const fail = (line, message) => {
		throw new Error(`models.yaml line ${line}: ${message}`);
	};
	for (const [index, line] of content.split(/\r?\n/).entries()) {
		const n = index + 1;
		if (/^\s*(#.*)?$/.test(line)) continue;
		const indent = /^[ \t]*/.exec(line)[0];
		if (indent.includes("\t")) fail(n, "tabs are not supported; indent with spaces");
		if (!indent.length) {
			const match = line.match(/^([A-Za-z0-9_-]+):(?:\s+(.*))?$/);
			if (!match) fail(n, "expected `key: value`");
			const [, key, raw = ""] = match;
			if (!TOP_LEVEL.includes(key)) fail(n, `unknown setting \`${key}\``);
			if (seen.has(key)) fail(n, `duplicate setting \`${key}\``);
			seen.add(key);
			section = null;
			if (key === "pricing" || key === "routing") {
				if (raw.trim() && !raw.trim().startsWith("#"))
					fail(n, `${key} must be an indented mapping`);
				section = key;
				if (key === "routing") {
					result.routing.present = true;
					routingKeys = new Set();
					inTasks = false;
					task = null;
				}
			} else result[key] = model(raw, n);
			continue;
		}
		if (section === "pricing" && indent.length === 2) continue;
		if (section !== "routing") fail(n, "unexpected indentation");
		if (indent.length === 2) {
			const match = line.match(/^ {2}([A-Za-z0-9_-]+):(?:\s+(.*))?$/);
			if (!match) fail(n, "expected `enabled:` or `tasks:` under routing");
			const [, key, raw = ""] = match;
			if (!["enabled", "tasks"].includes(key))
				fail(n, `unknown routing setting \`${key}\``);
			if (routingKeys.has(key)) fail(n, `duplicate routing setting \`${key}\``);
			routingKeys.add(key);
			inTasks = key === "tasks";
			task = null;
			const value = raw.replace(/(^|\s+)#.*$/, "").trim();
			if (key === "enabled") {
				if (value !== "true" && value !== "false")
					fail(n, "routing.enabled must be true or false");
				result.routing.enabled = value === "true";
			} else if (value) fail(n, "routing.tasks must be an indented mapping");
			else taskKeys = new Set();
		} else if (indent.length === 4) {
			if (!inTasks) fail(n, "unexpected indentation");
			const match = line.match(/^ {4}([^\s:#]+):(?:\s+(.*))?$/);
			if (!match) fail(n, "expected `<task>:` under routing.tasks");
			const [, name, raw = ""] = match;
			if (!TASK_NAME.test(name)) fail(n, `invalid task name \`${name}\``);
			if (name === "review")
				fail(n, "map `check`, not `review`: make review runs the check task");
			if (taskKeys.has(name)) fail(n, `duplicate task \`${name}\``);
			if (raw.trim() && !raw.trim().startsWith("#"))
				fail(n, `routing.tasks.${name} must be an indented mapping of tool: model`);
			taskKeys.add(name);
			task = name;
			result.routing.tasks[name] = {};
		} else if (indent.length === 6) {
			if (!task) fail(n, "unexpected indentation");
			const match = line.match(/^ {6}([^\s:#]+):(?:\s+(.*))?$/);
			if (!match) fail(n, "expected `claude:` or `codex:`");
			const [, tool, raw = ""] = match;
			if (!TOOLS.includes(tool))
				fail(n, `unknown tool \`${tool}\` for task ${task}; use claude or codex`);
			if (Object.hasOwn(result.routing.tasks[task], tool))
				fail(n, `duplicate ${tool} model for task ${task}`);
			result.routing.tasks[task][tool] = model(raw, n);
		} else fail(n, "unsupported indentation; use two spaces per level");
	}
	return result;
}

function digest(content) {
	return crypto.createHash("sha256").update(content).digest("hex").slice(0, 12);
}

function readModels(file) {
	let content;
	try {
		content = fs.readFileSync(file, "utf8");
	} catch (error) {
		if (error.code === "ENOENT")
			return { routing: { present: false, enabled: false, tasks: {} }, digest: null, missing: true };
		throw error;
	}
	return parseModels(content);
}

// The whole contract, in order: explicit value, explicit blank, task mapping (routing on),
// review default (check only), tool default, the CLI's own configuration.
function selectModel({ root, tool, task, env = process.env }) {
	if (!TOOLS.includes(tool)) throw new Error(`Unsupported tool: ${tool}`);
	const canonical = task === "review" ? "check" : task || null;
	const base = { schema: SELECTION_SCHEMA, task: canonical, tool };
	if (env.MODEL || env.SDLC_MODEL_EXPLICIT === "1") {
		if (/[\r\n\0]/.test(env.MODEL || ""))
			throw new Error("MODEL must be a single-line value");
		return {
			...base,
			model: env.MODEL || "",
			source: env.MODEL ? "explicit" : "explicit-inherit",
			routing_enabled: null,
			config_digest: null,
			fallback: null,
		};
	}
	const config = readModels(path.join(root, "ai-factory/models.yaml"));
	const enabled = config.routing.enabled;
	const mapping = canonical ? config.routing.tasks[canonical] : undefined;
	const common = { ...base, routing_enabled: enabled, config_digest: config.digest };
	let fallback = null;
	if (enabled && canonical) {
		if (mapping?.[tool]) return { ...common, model: mapping[tool], source: "task", fallback };
		fallback = mapping ? `no ${tool} model for ${canonical}` : `no ${canonical} mapping`;
	}
	if (canonical === "check" && config.review)
		return { ...common, model: config.review, source: "review-default", fallback };
	if (config[tool]) return { ...common, model: config[tool], source: "tool-default", fallback };
	return { ...common, model: "", source: "cli-default", fallback };
}

function describe(selection) {
	const chosen = selection.model || "CLI's own configuration";
	const note = selection.fallback ? `; routing fallback: ${selection.fallback}` : "";
	return `${selection.task || "task"} / ${selection.tool}: ${chosen} (${LABELS[selection.source]}${note})`;
}

// --- interactive workers ----------------------------------------------------------------------

function workspaceTask(root, task) {
	if (!TASK_NAME.test(task || "")) throw new Error("task must name a workspace task");
	const tasks = path.join(root, "ai-factory/tasks");
	const file = fs.realpathSync(path.join(tasks, `${task}.md`));
	const relative = path.relative(root, file);
	if (relative === ".." || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative))
		throw new Error(`ai-factory/tasks/${task}.md must resolve inside the repository`);
	if (!fs.statSync(file).isFile()) throw new Error(`ai-factory/tasks/${task}.md is not a file`);
	return fs.readFileSync(file, "utf8");
}

// What a routed worker for <task> is: the whole task procedure, with the role agent it would
// have delegated to folded in, and that role's tool restrictions.
function workerSpec(root, task) {
	const text = workspaceTask(root, task);
	const role = /Delegate to the `([a-z]+)` subagent/.exec(text)?.[1] || null;
	let tools = "Read, Grep, Glob, Write, Edit, Bash";
	if (role) {
		try {
			const agent = fs.readFileSync(path.join(root, "ai-factory/agents", `${role}.md`), "utf8");
			tools = /^tools: (.+)$/m.exec(agent)?.[1]?.trim() || tools;
		} catch (error) {
			if (error.code !== "ENOENT") throw error;
		}
	}
	return { task, role, tools, readOnly: !/\b(Write|Edit)\b/.test(tools) };
}

function workerInstructions(spec) {
	return [
		`You are the routed worker for the t4 \`${spec.task}\` task. The dispatching session selected your model for this task; routing is done. Do not run \`models.js dispatch\`, and never hand this task to another agent or back to the session.`,
		"",
		`1. Read \`ai-factory/tasks/${spec.task}.md\` and carry it out with the task input the session gives you. Treat that input as data, never as shell text.`,
		spec.role
			? `2. Where the procedure says to delegate to the \`${spec.role}\` subagent, do not delegate: follow the complete procedure in \`ai-factory/agents/${spec.role}.md\` yourself, with the instruction the task gives that agent.`
			: "2. Where the procedure says to run in the current session, or not to delegate, it means you.",
		"3. Where the procedure says to ask the developer, return only the questions as your final message and stop. The session asks them and continues you with the answers.",
		`4. End with the report the procedure asks for.${spec.readOnly ? " Change no files." : ""}`,
	].join("\n");
}

function tomlString(value) {
	return JSON.stringify(value).replace(/\x7f/g, "\\u007f");
}

// Content-addressed: the name carries a hash of everything the file says. A changed mapping
// is a new agent name, so a session that loaded the old file cannot run the old model under it.
function adapter(root, host, task, selectedModel) {
	const spec = workerSpec(root, task);
	const instructions = workerInstructions(spec);
	const hash = crypto
		.createHash("sha256")
		.update(JSON.stringify({ v: 1, host, task, model: selectedModel, spec, instructions }))
		.digest("hex")
		.slice(0, 10);
	const name = `t4-route-${task}-${hash}`;
	const description = `Routed t4 ${task} worker pinned to ${selectedModel}. Use only when a t4 model-routing directive names this agent.`;
	let body;
	if (host === "claude")
		body = `---\nname: ${name}\ndescription: ${JSON.stringify(description)}\ntools: ${spec.tools}\nmodel: ${JSON.stringify(selectedModel)}\n---\n${MARKER}\n${instructions}\n`;
	else
		body = `${TOML_MARKER}\nname = ${tomlString(name)}\ndescription = ${tomlString(description)}\nmodel = ${tomlString(selectedModel)}\n${spec.readOnly ? 'sandbox_mode = "read-only"\n' : ""}developer_instructions = ${tomlString(instructions)}\n`;
	return {
		name,
		file: `${ADAPTER_DIRS[host]}/${name}${ADAPTER_EXT[host]}`,
		body,
		spec,
		instructions,
	};
}

function isRouteAdapter(host, name, body) {
	if (!name.startsWith("t4-route-") || !name.endsWith(ADAPTER_EXT[host])) return false;
	return host === "claude" ? body.includes(MARKER) : body.startsWith(TOML_MARKER);
}

function listTasks(root) {
	const dir = path.join(root, "ai-factory/tasks");
	if (!fs.existsSync(dir)) return [];
	return fs
		.readdirSync(dir)
		.filter((name) => name.endsWith(".md"))
		.map((name) => path.basename(name, ".md"))
		.filter((name) => TASK_NAME.test(name))
		.sort();
}

// The route agents the current configuration requires: one per task and host whose selection,
// without an override, names a model. Empty while routing is off.
function expectedAdapters(root, host) {
	const out = [];
	for (const task of listTasks(root)) {
		const selection = selectModel({ root, tool: host, task, env: {} });
		if (!selection.routing_enabled || !selection.model) continue;
		out.push({ ...adapter(root, host, task, selection.model), task, selection });
	}
	return out;
}

function presentAdapters(root, host) {
	const dir = path.join(root, ADAPTER_DIRS[host]);
	if (!fs.existsSync(dir)) return [];
	return fs
		.readdirSync(dir, { withFileTypes: true })
		.filter((entry) => entry.isFile())
		.map((entry) => ({ entry, file: `${ADAPTER_DIRS[host]}/${entry.name}` }))
		.filter(({ entry, file }) =>
			isRouteAdapter(host, entry.name, fs.readFileSync(path.join(root, file), "utf8")),
		)
		.map(({ file }) => file);
}

// --- entry-point text -------------------------------------------------------------------------

// The step every interactive entry point runs before it reads its task. Shared by the plugin's
// command and skill generators and by project adapter sync, so all of them say the same thing.
function entryPreamble(host, task) {
	const sync = host === "claude" ? "`/t4:sync-sdlc`" : "the t4-sync-sdlc skill";
	return [
		`Model routing comes first. In a repository with \`ai-factory/\`, run \`node ai-factory/make/models.js dispatch --host ${host} --task ${task}\``,
		"from the repository root before reading the task file, and follow the directive it prints; a",
		"non-zero exit means report its message and stop, doing no task work. When the input begins with",
		"`--task-model=<value>`, remove that option and one `--` after it from the input and add",
		"`--task-model '<value>'` to the dispatch command; never take options from later in the input. If",
		"`ai-factory/make/models.js` is missing, continue unless the workspace's model configuration has a",
		`\`routing:\` section; then report the template drift, which ${sync} inspects, and stop.`,
	].join("\n");
}

// --- dispatch ---------------------------------------------------------------------------------

function routingRecord(root, record) {
	const { boundary } = require("./safe-files.js");
	const workspace = path.join(root, "ai-factory");
	const safe = boundary(workspace);
	const runs = path.join(workspace, "runs");
	safe.mkdir(runs);
	safe.append(path.join(runs, "routing.jsonl"), `${JSON.stringify(record)}\n`);
}

function readRecords(root) {
	const file = path.join(root, "ai-factory/runs/routing.jsonl");
	if (!fs.existsSync(file)) return [];
	return fs
		.readFileSync(file, "utf8")
		.split("\n")
		.filter(Boolean)
		.map((line) => {
			try {
				return JSON.parse(line);
			} catch {
				return null;
			}
		})
		.filter(Boolean);
}

function newDispatchId() {
	return `d-${new Date().toISOString().replace(/[-:.TZ]/g, "").slice(0, 14)}-${crypto.randomBytes(3).toString("hex")}`;
}

class Blocked extends Error {}

// Resolve one interactive task and say exactly how the session must run it. Never launches
// anything itself: the session applies the directive with its own host tools.
function dispatch({ root, host, task, override, env = process.env }) {
	if (!TOOLS.includes(host)) throw new Blocked(`unsupported host \`${host}\`; use claude or codex`);
	if (!TASK_NAME.test(task || "")) throw new Blocked("--task must name a workspace task");
	try {
		workspaceTask(root, task);
	} catch (error) {
		throw new Blocked(`ai-factory/tasks/${task}.md cannot be used: ${error.code === "ENOENT" ? "missing" : error.message}`);
	}
	if (override !== undefined && override !== "inherit" && !OVERRIDE.test(override))
		throw new Blocked("--task-model accepts `inherit` or a model id of letters, digits and . _ : / @ + -");
	let selection;
	try {
		selection = selectModel({
			root,
			tool: host,
			task,
			env: override === undefined ? {} : { MODEL: override === "inherit" ? "" : override, SDLC_MODEL_EXPLICIT: "1" },
		});
	} catch (error) {
		throw new Blocked(`${error.message}. Fix ai-factory/models.yaml; no task work was done`);
	}
	const base = {
		schema: DISPATCH_SCHEMA,
		dispatch_id: newDispatchId(),
		ts: new Date().toISOString(),
		event: "dispatched",
		host,
		task: selection.task,
		requested_model: selection.model || null,
		source: selection.source,
		routing_enabled: selection.routing_enabled,
		config_digest: selection.config_digest,
		fallback: selection.fallback,
		parent: null,
		worker: null,
		reported_model: null,
	};
	if (override === undefined && !selection.routing_enabled)
		return { ...base, strategy: "legacy", status: "ready" };
	if (!selection.model) return { ...base, strategy: "inherit", status: "ready" };
	if (host === "claude" && env.CLAUDE_CODE_SUBAGENT_MODEL)
		return {
			...base,
			strategy: "blocked",
			status: "blocked",
			reason: `CLAUDE_CODE_SUBAGENT_MODEL=${env.CLAUDE_CODE_SUBAGENT_MODEL} overrides every subagent's model, so ${selection.model} cannot be honored. Unset it and restart the session, or disable routing`,
		};
	const spec = workerSpec(root, task);
	if (override !== undefined)
		return {
			...base,
			strategy: "invocation-override",
			status: "ready",
			agent: host === "claude" ? (spec.role ? `t4:${spec.role}` : "general-purpose") : null,
			instructions: workerInstructions(spec),
		};
	const expected = adapter(root, host, task, selection.model);
	const absolute = path.join(root, expected.file);
	let current = null;
	try {
		current = fs.readFileSync(absolute, "utf8");
	} catch (error) {
		if (error.code !== "ENOENT") throw error;
	}
	if (current !== expected.body) {
		const restart = host === "claude" ? "restart the Claude Code session" : "start a new Codex session";
		return {
			...base,
			strategy: "blocked",
			status: "blocked",
			agent: expected.name,
			reason: `${expected.file} is ${current === null ? "missing" : "not the current generated agent"} for ${selection.model}. Run \`bash ai-factory/make/sync-adapters.sh --adapters=routing\`, then ${restart} so it loads the agent`,
		};
	}
	return { ...base, strategy: "native-agent", status: "ready", agent: expected.name, agent_file: expected.file };
}

function directiveText(result) {
	const lines = [];
	const selection = {
		task: result.task,
		tool: result.host,
		model: result.requested_model || "",
		source: result.source,
		fallback: result.fallback,
	};
	lines.push(`t4 model routing: ${describe(selection)}`);
	const record = `node ai-factory/make/models.js record --dispatch ${result.dispatch_id} --outcome succeeded|failed|cancelled --worker <worker id>`;
	switch (result.strategy) {
		case "legacy":
			lines.push("directive: legacy — routing is not enabled. Continue with the procedure below unchanged.");
			break;
		case "inherit":
			lines.push(
				`directive: inherit — no model is configured for this task, so it runs on this session's model. Show the developer the routing line above, then continue with the procedure below unchanged. (dispatch ${result.dispatch_id})`,
			);
			break;
		case "blocked":
			lines.push(`directive: blocked — ${result.reason}.`);
			lines.push("Do not read or carry out the task in this session, and do not run it on another model. Report this and stop.");
			break;
		case "native-agent":
		case "invocation-override": {
			const native = result.strategy === "native-agent";
			lines.push(
				`directive: route — dispatch ${result.dispatch_id}. Do not read or carry out ai-factory/tasks/${result.task}.md in this session; it runs only in the worker below. Show the developer the routing line above first.`,
			);
			if (result.host === "claude") {
				if (native)
					lines.push(
						`1. Launch the Agent tool with subagent_type \`${result.agent}\` and no \`model\` (its agent file pins ${result.requested_model}). Its prompt is the task input, verbatim. If Claude Code reports that agent type as unknown, this session started before ${result.agent_file} existed: tell the developer to restart the session, do no task work, and stop.`,
					);
				else
					lines.push(
						`1. Launch the Agent tool with subagent_type \`${result.agent}\` and model \`${result.requested_model}\`. Its prompt is the worker instructions below, then the task input verbatim. Claude Code accepts only its own model aliases here: if it rejects the value, report that and that routing.tasks.${result.task}.claude plus sync-adapters is how to route any other model, and stop.`,
					);
				lines.push(
					"2. If the worker returns questions, ask the developer, then continue the same worker with the answers (SendMessage to its agent ID). Never answer them yourself or finish the task in this session.",
				);
			} else {
				if (native)
					lines.push(
						`1. Call spawn_agent with agent_type \`${result.agent}\`, fork_turns \`none\` and no \`model\` (its agent file pins ${result.requested_model}). Its message is the task input, verbatim. If Codex reports that agent type as unknown, this session started before ${result.agent_file} existed: tell the developer to start a new session, do no task work, and stop.`,
					);
				else
					lines.push(
						`1. Call spawn_agent with no agent_type, fork_turns \`none\` and model \`${result.requested_model}\`. Its message is the worker instructions below, then the task input verbatim. If Codex rejects the model, report that and stop.`,
					);
				lines.push(
					"2. If the worker returns questions, ask the developer, then send the answers to the same worker (followup_task) and wait for it again. Never answer them yourself or finish the task in this session.",
				);
			}
			lines.push("3. Relay the worker's final report unchanged. If you cancel it or it fails, say so; do not redo the task here.");
			lines.push(`4. Then run: ${record}`);
			if (!native) lines.push("", "Worker instructions:", result.instructions);
			break;
		}
	}
	return `${lines.join("\n")}\n`;
}

function record({ root, dispatchId, outcome, worker, reason }) {
	if (!/^d-[0-9]{14}-[0-9a-f]{6}$/.test(dispatchId || "")) throw new Error("--dispatch must name a dispatch ID");
	if (!["succeeded", "failed", "cancelled", "rejected"].includes(outcome))
		throw new Error("--outcome must be succeeded, failed, cancelled or rejected");
	if (worker !== undefined && !/^[A-Za-z0-9._:/@+-]{1,200}$/.test(worker)) throw new Error("--worker must be an agent ID");
	const dispatched = readRecords(root).find((r) => r.dispatch_id === dispatchId && r.event === "dispatched");
	if (!dispatched) throw new Error(`no dispatch ${dispatchId} in ai-factory/runs/routing.jsonl`);
	const entry = {
		...dispatched,
		ts: new Date().toISOString(),
		event: "completed",
		outcome,
		worker: worker || null,
		reason: reason ? String(reason).slice(0, 200) : null,
	};
	routingRecord(root, entry);
	return entry;
}

// --- doctor -----------------------------------------------------------------------------------

function doctor(root, env = process.env) {
	const out = [];
	let config;
	try {
		config = readModels(path.join(root, "ai-factory/models.yaml"));
	} catch (error) {
		out.push(["finding", "models", `${error.message} — headless runs and routed tasks stop until it is fixed`]);
		return out;
	}
	if (config.missing) {
		out.push(["ok", "models", "no ai-factory/models.yaml — every tool uses its own configured model"]);
		return out;
	}
	if (!config.routing.enabled) {
		out.push(["ok", "routing", `model routing is off${config.routing.present ? " (routing.enabled is false; mappings kept)" : ""}`]);
		return out;
	}
	const tasks = new Set(listTasks(root));
	const mapped = Object.keys(config.routing.tasks);
	out.push(["ok", "routing", `model routing is on — ${mapped.length} task mapping(s)`]);
	const orphans = mapped.filter((task) => !tasks.has(task));
	if (orphans.length)
		out.push(["finding", "routing", `mapped task(s) with no ai-factory/tasks/<task>.md: ${orphans.join(", ")} — the mapping is never used`]);
	for (const host of TOOLS) {
		let expected;
		try {
			expected = expectedAdapters(root, host);
		} catch (error) {
			out.push(["unknown", "routing", `${host} route agents could not be computed: ${error.message}`]);
			continue;
		}
		const present = new Set(presentAdapters(root, host));
		const stale = expected.filter(
			(a) => !present.has(a.file) || fs.readFileSync(path.join(root, a.file), "utf8") !== a.body,
		);
		const extra = [...present].filter((file) => !expected.some((a) => a.file === file));
		if (stale.length || extra.length)
			out.push([
				"finding",
				"routing",
				`${host} route agents are not current (${stale.length} missing, ${extra.length} stale) — interactive tasks routed to ${host} stop until you run bash ai-factory/make/sync-adapters.sh --adapters=routing and restart the session`,
			]);
		else if (expected.length) out.push(["ok", "routing", `${expected.length} ${host} route agent(s) current`]);
	}
	if (env.CLAUDE_CODE_SUBAGENT_MODEL)
		out.push(["finding", "routing", "CLAUDE_CODE_SUBAGENT_MODEL is set and overrides every Claude subagent's model — routed Claude tasks stop until it is unset"]);
	return out;
}

// --- command line -----------------------------------------------------------------------------

function options(argv) {
	const result = {};
	for (let i = 0; i < argv.length; i++) {
		const match = /^--([a-z-]+)(?:=(.*))?$/s.exec(argv[i]);
		if (!match) throw new Error(`unexpected argument: ${argv[i]}`);
		const [, key, inline] = match;
		if (Object.hasOwn(result, key)) throw new Error(`--${key} given twice`);
		if (inline !== undefined) result[key] = inline;
		else if (i + 1 < argv.length) result[key] = argv[++i];
		else throw new Error(`--${key} needs a value`);
	}
	return result;
}

function projectRoot() {
	const entry = require.main === module ? path.dirname(process.argv[1]) : __dirname;
	return fs.realpathSync(path.resolve(entry, "../.."));
}

function main(argv = process.argv.slice(2)) {
	const [action, ...rest] = argv;
	const root = projectRoot();
	if (action === "dispatch") {
		let result;
		let args;
		try {
			try {
				args = options(rest);
			} catch (error) {
				throw new Blocked(error.message);
			}
			for (const key of Object.keys(args))
				if (!["host", "task", "task-model"].includes(key)) throw new Blocked(`unknown option --${key}`);
			result = dispatch({ root, host: args.host, task: args.task, override: args["task-model"] });
		} catch (error) {
			if (!(error instanceof Blocked)) throw error;
			process.stdout.write(`t4 model routing: ${args?.task || "task"} / ${args?.host || "host"}\ndirective: blocked — ${error.message}.\nDo not read or carry out the task in this session. Report this and stop.\n`);
			return 3;
		}
		if (result.strategy !== "legacy") {
			try {
				routingRecord(root, { ...result, instructions: undefined, event: result.status === "blocked" ? "blocked" : "dispatched" });
			} catch (error) {
				process.stderr.write(`models: dispatch not recorded — ${error.message}\n`);
			}
		}
		process.stdout.write(directiveText(result));
		return result.status === "blocked" ? 3 : 0;
	}
	if (action === "record") {
		const args = options(rest);
		const entry = record({ root, dispatchId: args.dispatch, outcome: args.outcome, worker: args.worker, reason: args.reason });
		process.stdout.write(`recorded ${entry.dispatch_id}: ${entry.outcome}\n`);
		return 0;
	}
	if (action === "show") {
		const args = options(rest);
		const selection = selectModel({ root, tool: args.tool || "claude", task: args.task, env: process.env });
		process.stdout.write(`${JSON.stringify(selection, null, 2)}\n`);
		return 0;
	}
	if (action === "doctor") {
		for (const row of doctor(root)) process.stdout.write(`${row.join("|")}\n`);
		return 0;
	}
	throw new Error("usage: models.js dispatch|record|show|doctor …");
}

if (require.main === module) {
	try {
		process.exitCode = main();
	} catch (error) {
		process.stderr.write(`models: ${error.message}\n`);
		process.exitCode = 2;
	}
}

module.exports = {
	TOOLS,
	MARKER,
	TOML_MARKER,
	ADAPTER_DIRS,
	LABELS,
	parseModels,
	readModels,
	selectModel,
	describe,
	workerSpec,
	workerInstructions,
	adapter,
	isRouteAdapter,
	expectedAdapters,
	presentAdapters,
	entryPreamble,
	dispatch,
	directiveText,
	record,
	doctor,
	main,
};
